#!/bin/sh
# Copyright (c) 2020 Sebastian LaVine <mail@smlavine.com>
# Licensed under the GNU GPLv3. See smlss/GPLv3.txt for details.
#
# File:        addpackage
# Description: Add the given package to smlss's install lists.
# Options:     -a	Add packages to the AUR list, not the Arch list.
# Arguments:   names of packages to add

options="ah"
while getopts "$options" o; do
	case "$o" in
		a) aur="True" ;;
		*) echo "USAGE: addpackage [-$options] packages..." && exit ;;
	esac
done

shift $(($OPTIND - 1))
packages="$(echo "$*" | tr ' ' '\n')"
file='packages.txt'
[ "$aur" ] && file="aur-$file"
cd ~/smlss # temporarily relocate to add to install lists and to make the commit

echo -e "$packages" >> $file &&
	sort $file | sponge $file &&
	git add $file

# Change newlines to commas to make the list presentable for a git commit
packages="$(echo $packages | sed 's/\\n/, /g')"

commitmsg="[$file] Add $packages"
# Remove trailing comma from package list
commitmsg="$(echo $commitmsg | sed 's/,$//')"

git commit -vem "$commitmsg"

cd - # teleport home

