#!/bin/sh
# Copyright (c) 2019-2021 Sebastian LaVine <mail@smlavine.com>
# Licensed under the MIT license. See smlss/MIT.txt for details.
#
# File:        lastscreenshot
# Description: Opens the last screenshot taken in sxiv, and queues all previous
#              screenshots to be viewed.

# Directory containing the screenshots.
screenshot_path="$HOME/Documents/pictures/screenshots/"

cd "$screenshot_path"

sxiv $(ls -A1t)

cd -
