#!/usr/bin/env python3
# Copyright (c) 2020 Sebastian LaVine <seblavine@outlook.com>
# Licensed under the MIT license. See smlss/LICENSE for details.
#
# File: limit
# Arguments: expression, n
# Description: For a given expression with variable x, find the limit of the
#              expression as x approaches n.

from sys import argv
from sympy import symbols, limit
from sympy.parsing.sympy_parser import parse_expr

if len(argv) != 3:
    print("Usage: limit expression n")
    exit()

n = float(argv[2])
expr = parse_expr(argv[1])
x = symbols("x")

left = limit(expr, x, n, "-")
right = limit(expr, x, n, "+")

if (left == right):
    print(left)
else:
    print("Left: {}\nRight: {}".format(left, right))

