#!/bin/sh
# Copyright (c) 2021 Sebastian LaVine <mail@smlavine.com>
# Licensed under the MIT license. See smlss/MIT.txt for details.
#
# File:        mypassmenu
# Description: Opens a stylized dmenu prompt with passwords to select from.

passmenu -i -c -fn 20 -sb '#b00' -l 30
