#!/bin/sh
# Copyright (c) 2019-2020 Sebastian LaVine <seblavine@outlook.com>
# Licensed under the MIT license. See smlss/LICENSE for details.
#
# File: new
# Description: Opens a new program, called by the program arguments.

nohup "$@" >/dev/null &
