#!/bin/sh
# Copyright (c) 2019-2021 Sebastian LaVine <mail@smlavine.com>
# Licensed under the MIT license. See smlss/MIT.txt for details.
#
# File:        new
# Description: Opens a new program, called by the program arguments.

nohup "$@" >/dev/null &
