#!/bin/sh
# Copyright (c) 2019-2020 Sebastian LaVine <mail@smlavine.com>
# Licensed under the MIT license. See smlss/MIT.txt for details.
#
# File:        shoot
# Description: Saves a screenshot as PNG. Intended for use with a keybind.
# Options:     -d	Prompts for filename with dmenu instead of
#                	using timestamp.

picture_path="$HOME/Documents/pictures/screenshots/"

# take picture as soon as possible
file="$(mktemp)"
xwd -root | convert xwd:- png:"$file"

# read name from dmenu
if [ "$1" = "-d" ]
then
	# read from /dev/null so that it doesn't block for input
    name=$(dmenu -p "Name?" < /dev/null) 
fi

# either "-d" not used, OR dmenu cancelled out before input:
# generate name based on time taken
if [ "$name" = "" ]
then
	# example: "screenshot2019-11-17.948921698"
	name="screenshot$(date '+%F.%N')"
fi

[ -d "$picture_path" ] && mv "$file" "$picture_path/$name.png" ||
	mv "$file" "$HOME/$name.png"


