#!/bin/sh
# Copyright (C) 2019-2020 Sebastian LaVine <seblavine@outlook.com>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# File:        vol
# Description: Sets the system volume.
# Arguments:   argument to amixer (ex. 40%, 500, 5%+, 6%-)

# if there are no arguments, output the percentage volumes of left/right Master
[ $# -eq 0 ] &&
	amixer sget Master | # A paragraph containing lots of sound info
	sed 1,4d | # Strips to the two lines containing left and right volume
	awk '{ print $5 }' | # Only print word containing volume percentage
	tr -s '[]%\n' '.' && # Replace delimiter characters with periods
	exit
# else, set the audio according to the first argument
amixer -q set Master "$1"
