#!/bin/sh
# Copyright (c) 2020-2021 Sebastian LaVine <mail@smlavine.com>
# Licensed under the GNU GPLv3. See smlss/GPLv3.txt for details.
#
# File:        watchyt
# Description: Watch the given YouTube video in mpv, using youtube-dl.
# Options:     -c	Use the clipboard value as the video URL.
#              -d	Open the video description in less. (don't launch mpv)
# Arguments:   URL of the video to watch

dpywidth=$(xdpyinfo | awk '/dimensions/ {print $2}' | cut -d'x' -f1)
dpyheight=$(xdpyinfo | awk '/dimensions/ {print $2}' | cut -d'x' -f2)

while getopts "cdh" o; do
	case "$o" in
		c) url="$(xclip -selection c -o)" ;;
		d) description="True" ;;
		*) printf "USAGE: watchyt [-cd] [url]\n" && exit 2 ;;
	esac
done

# I didn't know this existed until I read the getopts man page. It's useful!
shift $(($OPTIND - 1))

# Only set the url if it isnt already set through the clipboard.
[ "$url" ] || url="$*"

# Remove any chars that are not letters, numbers, or punctuation from the url.
url="$(echo "$url" | tr -cd '[:alnum:][:punct:]' )"

if [ "$description" ]; then
	descfile="$(mktemp watchyt.XXXXXXXX -p /tmp)"
	youtube-dl --get-description "$url" > "$descfile"
	st -e less "$descfile"
	rm "$descfile" # Once less is closed, then delete file.
	exit # Don't open the video in mpv.
fi

mpv --ytdl-raw-options=format="best[height<=?$dpyheight][width<=?$dpywidth]" \
	ytdl://"$url"

