#!/bin/sh
# Copyright (c) 2020 Sebastian LaVine <mail@smlavine.com>
# Licensed under the GNU GPLv3. See smlss/GPLv3.txt for details.
#
# File:        watchyt
# Description: Watch the given YouTube video in mpv, using youtube-dl.
# Options:     -c	Use the clipboard value as the video URL.
#              -d	Open the description of the video in a pager.
# Arguments:   URL of the video to watch

dpywidth=$(xdpyinfo | awk '/dimensions/ {print $2}' | cut -d'x' -f1)
dpyheight=$(xdpyinfo | awk '/dimensions/ {print $2}' | cut -d'x' -f2)

while getopts "cdh" o; do
	case "$o" in
		# Look for a URL in all three xclip selections, and choose one which
		# has "youtu" in it, because all YT URLs have that string.
		c) url="$(printf "$(xclip -selection p -o)\n$(xclip -selection s -o)\n$(xclip -selection c -o)" | grep youtu | head -1)" ;;
		d) description="True" ;;
		*) printf "USAGE: watchyt [-cd] [url]\n" && exit 2 ;;
	esac
done

# I didn't know this existed until I read the getopts man page. It's useful!
shift $(($OPTIND - 1))

# Only set the url if it isnt already set through the clipboard.
[ "$url" ] || url="$*"

mpv --ytdl-raw-options=format="best[height<=?$dpyheight][width<=?$dpywidth]" \
	ytdl://"$url" &
	if [ "$description" ]; then
		descfile="$(mktemp watchyt.XXXXXXXX -p /tmp)"
		youtube-dl --get-description "$url" > "$descfile"
		st -e less "$descfile"
		rm "$descfile" # Once description window is closed, then delete file.
	fi && exit # explicit exit call to return to shell after '&' above

